info:
  title: Simple API overview
  version: 2.0.0
openapi: 3.0.0
paths:
  /:
    get:
      operationId: listVersionsv2
      responses:
        '200':
          content:
            application/json:
              examples:
                foo:
                  value:
                    versions:
                    - id: v2.0
                      links:
                      - href: http://127.0.0.1:8774/v2/
                        rel: self
                      status: CURRENT
                      updated: '2011-01-21T11:33:21Z'
                    - id: v3.0
                      links:
                      - href: http://127.0.0.1:8774/v3/
                        rel: self
                      status: EXPERIMENTAL
                      updated: '2013-07-23T11:33:21Z'
          description: 200 response
        '300':
          content:
            application/json:
              examples:
                foo:
                  value: "{\n \"versions\": [\n       {\n         \"status\": \"CURRENT\"\
                    ,\n         \"updated\": \"2011-01-21T11:33:21Z\",\n         \"\
                    id\": \"v2.0\",\n         \"links\": [\n             {\n     \
                    \            \"href\": \"http://127.0.0.1:8774/v2/\",\n      \
                    \           \"rel\": \"self\"\n             }\n         ]\n  \
                    \   },\n     {\n         \"status\": \"EXPERIMENTAL\",\n     \
                    \    \"updated\": \"2013-07-23T11:33:21Z\",\n         \"id\":\
                    \ \"v3.0\",\n         \"links\": [\n             {\n         \
                    \        \"href\": \"http://127.0.0.1:8774/v3/\",\n          \
                    \       \"rel\": \"self\"\n             }\n         ]\n     }\n\
                    \ ]\n}\n"
          description: 300 response
      summary: List API versions
  /v2:
    get:
      operationId: getVersionDetailsv2
      responses:
        '200':
          content:
            application/json:
              examples:
                foo:
                  value:
                    version:
                      id: v2.0
                      links:
                      - href: http://127.0.0.1:8774/v2/
                        rel: self
                      - href: http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf
                        rel: describedby
                        type: application/pdf
                      - href: http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl
                        rel: describedby
                        type: application/vnd.sun.wadl+xml
                      - href: http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl
                        rel: describedby
                        type: application/vnd.sun.wadl+xml
                      media-types:
                      - base: application/xml
                        type: application/vnd.openstack.compute+xml;version=2
                      - base: application/json
                        type: application/vnd.openstack.compute+json;version=2
                      status: CURRENT
                      updated: '2011-01-21T11:33:21Z'
          description: 200 response
        '203':
          content:
            application/json:
              examples:
                foo:
                  value:
                    version:
                      id: v2.0
                      links:
                      - href: http://23.253.228.211:8774/v2/
                        rel: self
                      - href: http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf
                        rel: describedby
                        type: application/pdf
                      - href: http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl
                        rel: describedby
                        type: application/vnd.sun.wadl+xml
                      media-types:
                      - base: application/xml
                        type: application/vnd.openstack.compute+xml;version=2
                      - base: application/json
                        type: application/vnd.openstack.compute+json;version=2
                      status: CURRENT
                      updated: '2011-01-21T11:33:21Z'
          description: 203 response
      summary: Show API version details
