openapi: 3.1.0
info:
  title: Weather API
  version: 0.0.1
paths:
  /temperature/{city}:
    get:
      summary: Get temperature
      description: >
        Retrieves the current temperature in a specific city
        in celsius.
      parameters:
      - name: city
        in: path
        required: true
        schema:
          type: string 
          maxLength: 50
          example: "London"
      responses:
        "200":
          description: Retrieved weather data
          content:
            application/json:
              schema:
                type: integer
                minimum: -100
                maximum: 100
                example: 0
        "400":
          description: Could not retrieve data for given city
          content:
            text/html:
              schema:
                type: string
                maxLength: 256
                description: A message describing the error




